### ISSUE TITLE
Multiple Wordpress sites

### ISSUE THREAD

**Issue by bsmoo** [blakesmoore/CLBAccessList#1]
If there are multiple Wordpress sites which logging authentication errors to the same file, it will be hard to determine which site the request came from.

i.e. If a webmaster incorrectly logs into 3 different Wordpress sites, their IP address will be added to the ban.

**Comment by bsmoo** [comment]
The code for wp-fail2ban.php can be changed slightly to get each domain to log to its own log file, however it would cause manual work and you'll have to add an extra line to the jail everytime.

**Comment by bsmoo** [comment]
As Wordpress logs failed login requests as a 200 HTTP code, and successful login attempts as a 302 HTTP code, maybe it isn't nessescary to even install the plugin. We could just include the below as the failregex:

```
failregex = ^\"<HOST>, .* "POST .*wp-login.php HTTP/.*" 200
```

And we could then include the paths of logfiles we would like to monitor

```
[wordpress]

enabled   = true
port      = 80
filter    = wordpress
logpath   = /var/log/apache2/website1.co.uk-access.log
            /var/log/apache2/website2.co.uk-access.log
            /var/log/apache2/website3.co.uk-access.log
            /var/log/apache2/website4.co.uk-access.log
maxretry  = 3
banaction = rackspace-lb
findtime  = 120
bantime   = 3600
```

@eljrax - What are your thoughts?

**Comment by eljrax** [comment]
As long as that's consistently true, and there are no other circumstances where that could be true, then that does seem like a very good solution. 
Fewer dependencies is a win!

**Comment by bsmoo** [comment]
Closing this out as the way fail2ban operates does not allow multiple log paths. If you use multiple logpaths, fail2ban will use them aggregate all fails to make a decision on if it should ban the IP.
