### ISSUE TITLE
Load Balancer in PENDING_UPDATE

### ISSUE THREAD

**Issue by bsmoo** [blakesmoore/CLBAccessList#2]
If the load balancer has a status of 'PENDING_UPDATE' it is considered immutable.

Need to do a check on the LB status before adding and removing bans.

**Comment by eljrax** [comment]
Check this out:

https://github.com/eljrax/autoscale_setup/blob/master/load_balancing/remove_dead_nodes.py#L105L106

It will introduce another dependency for you, but will deal with it all for you. 

Alternatively wrap all requests in try: except: and implement your own method for polling the state. 
Even if you check the state before sending the request, you're still prone to race conditions, so you should ideally implement a re-try for certain conditions either way.

**Comment by bsmoo** [comment]
Thanks Erik
